manifest:
  remotes:
    # Define the Nordic remote source
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    # Import the official nRF Connect SDK manifest
    - name: sdk-nrf
      remote: ncs
      path: nrf
      revision: v3.2.1  # <--- LOCK YOUR VERSION HERE (e.g., v2.5.0, v2.7.0, main)
      import: true       # This imports all sub-dependencies (zephyr, mbedtls, etc.)
  
  self:
    # This defines where this repository (eno-os) will sit 
    # relative to the workspace root.
    path: eno-os